language:
      - ruby

before_script:
 - cd AbasteceAqui/
 - gem install rspec rspec-rails simplecov
 - bundle install

script:
        - bundle exec rspec spec
rvm:
  - 2.3.0

notifications:
  email:
    recipients:
      - jonatas_lenon@hotmail.com.br

branches:
  only:
  - Travis
